version: "3"
services:
       login-app:
           container_name: login-app
           image: latest123/login-app
           restart: always
           build: .
           ports:
             - "7500:7500"