# Dev version to build images locally
version: '2'
services:
  notekeeper:
    env_file: .env
    build: 
      context: ./apps/notekeeper
    restart: unless-stopped
    ports:
      - $REACT_APP_NOTEKEEPER_LOCAL_PORT:$REACT_APP_NOTEKEEPER_DOCKER_PORT
    networks:
      - backend
      - frontend
  keeper:
    depends_on:
      - notekeeper
    env_file: .env
    build:
      context: ./apps/keeper
      args:
        - REACT_APP_API_BASE_URL=$REACT_APP_NOTEKEEPER_HOSTIP
    ports:
      - $KEEPER_LOCAL_PORT:$KEEPER_DOCKER_PORT
    networks:
      - frontend  
volumes: 
  db:
networks:
  backend:
  frontend: