version: '2'
services:
  notekeeper:
    build: 
      context: ./apps/notekeeper
    restart: unless-stopped
    ports:
      - $NOTEKEEPER_LOCAL_PORT:$NOTEKEEPER_DOCKER_PORT
    networks:
      - backend
      - frontend
  keeper:
    depends_on:
      - notekeeper
    build:
      context: ./apps/keeper
      args:
        - REACT_APP_API_BASE_URL=$NOTEKEEPER_HOSTIP
    ports:
      - $KEEPER_LOCAL_PORT:$KEEPER_DOCKER_PORT
    networks:
      - frontend  
volumes: 
  db:
networks:
  backend:
  frontend: