name: ci

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/keeper:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/keeper:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/keeper:buildcache,mode=max

  deploy:
    runs-on: self-hosted

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          if_key_exists: ignore
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Checking connection
        run: ssh -q -o "BatchMode=yes" -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 2>&1" && echo $host SSH_OK || echo $host SSH_NOK

      - name: Checkout
        uses: actions/checkout@v2
      - name: Starting docker container
        run: docker run --rm -it -p 8080:80 mukkundsunjii/keeper:latest
