name: ci

on:
  push:
    branches:
      - master
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  REACT_IMAGE_NAME: keeper
  SERVER_IMAGE_NAME: notekeeper

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for React image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/ ${{ env.REACT_IMAGE_NAME }}

      - name: Build and push react docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./apps/${{ env.REACT_IMAGE_NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Extract metadata (tags, labels) for Server image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/ ${{ env.SERVER_IMAGE_NAME }}

      - name: Build and push react docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./apps/${{ env.SERVER_IMAGE_NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v1
    #     with:
    #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    #   - name: Set up Docker Build
    #     uses: docker/setup-buildx-action@v1
    #   - name: Build and push
    #     uses: docker/build-push-action@v2
    #     with:
    #       context: ./apps/keeper/
    #       file: ./apps/keeper/Dockerfile
    #       builder: ${{ steps.buildx.outputs.name }}
    #       push: true
    #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/keeper:latest
    #       cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/keeper:buildcache
    #       cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/keeper:buildcache,mode=max

  # deploy:
  #   runs-on: self-hosted
  #   needs: build

  #   steps:
  #     - name: Install SSH Key
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         known_hosts: "just-a-placeholder-so-we-dont-get-errors"
  #         if_key_exists: ignore
  #     - name: Adding Known Hosts
  #       run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

  #     - name: Checking connection
  #       run: ssh -q -o "BatchMode=yes" -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 2>&1" && echo $host SSH_OK || echo $host SSH_NOK

  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Copying the contents of the file
  #       run: scp -rp ~/actions-runner/_work/keeper/keeper/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/workdir/
  #     - name: Starting Keeper - React App
  #       run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run --rm -d -p 8080:80 mukkundsunjii/keeper:latest"
