name: ci

on:
  push:
    branches:
      - master
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  REACT_IMAGE_NAME: keeper
  SERVER_IMAGE_NAME: notekeeper

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push react image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/${{ env.REACT_IMAGE_NAME }}
          file: ./apps/${{ env.REACT_IMAGE_NAME }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REACT_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REACT_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REACT_IMAGE_NAME }}:buildcache,mode=max
      
      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/${{ env.SERVER_IMAGE_NAME }}
          file: ./apps/${{ env.SERVER_IMAGE_NAME }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVER_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVER_IMAGE_NAME }}:buildcache,mode=max

  # deploy:
  #   runs-on: self-hosted
  #   needs: build

  #   steps:
  #     - name: Install SSH Key
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         known_hosts: "just-a-placeholder-so-we-dont-get-errors"
  #         if_key_exists: ignore
  #     - name: Adding Known Hosts
  #       run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
  #     - name: Checking connection
  #       run: ssh -q -o "BatchMode=yes" -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 2>&1" && echo $host SSH_OK || echo $host SSH_NOK

  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Copying the contents of the file
  #       run: scp -rp ~/actions-runner/_work/keeper/keeper/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/workdir/
  #     - name: Starting Keeper - React App
  #       run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run --rm -d -p 8080:80 mukkundsunjii/keeper:latest"
